<?php
// generated by Poedit from fa_IR.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'fa_IR','pot-creation-date'=>'2025-09-25 16:28+0500','po-revision-date'=>'2026-04-29 18:13+0100','translation-revision-date'=>'2026-04-29 18:13+0100','project-id-version'=>'SB Chat','x-generator'=>'Poedit 3.9','messages'=>[]];
